/* generated by pull.js */
const manifest = {
  "name": "peak ai assistant",
  "description": "so skibidi rizz",
  "credits": [
    {
      "name": "Flufi"
    },
  ],
  "userscripts": [
    {
      "url": "userscript.js"
    }
  ],
  "userstyles": [
    {
      "url": "style.css"
    }
  ],
  "tags": [
    "recommended"
  ],
  "enabledByDefault": true
};
export default manifest;
